#!/usr/bin/env bun

const { spawn, stdin, stdout } = require("bun");

const args = process.argv.slice(2);

(async () => {
  const proc = spawn(["/bin/sh", "-c", args.join(" ")], {
    stdin: "pipe",
    stdout: "inherit",
    stderr: "inherit",
  });

  outputWriter = stdout.writer();

  for await (const chunk of stdin.stream()) {
    outputWriter.write(chunk);
    await proc.stdin.write(chunk);
  }

  proc.stdin.end();

  await proc.exited;
})();